var test = require('tape')
var abi = require('../abi')

test('getAbiFromTarget calculates correct Node ABI', function (t) {
  t.equal(abi.getAbiFromTarget(undefined), process.versions.modules)
  t.equal(abi.getAbiFromTarget(null), process.versions.modules)
  t.throws(function () { abi.getAbiFromTarget('a.b.c') })
  t.throws(function () { abi.getAbiFromTarget('1.0.0') })
  t.equal(abi.getAbiFromTarget('7.2.0'), '51')
  t.equal(abi.getAbiFromTarget('7.0.0'), '51')
  t.equal(abi.getAbiFromTarget('6.9.9'), '48')
  t.equal(abi.getAbiFromTarget('6.0.0'), '48')
  t.equal(abi.getAbiFromTarget('5.9.9'), '47')
  t.equal(abi.getAbiFromTarget('5.0.0'), '47')
  t.equal(abi.getAbiFromTarget('4.9.9'), '46')
  t.equal(abi.getAbiFromTarget('4.0.0'), '46')
  t.equal(abi.getAbiFromTarget('0.12.17'), '14')
  t.equal(abi.getAbiFromTarget('0.12.0'), '14')
  t.equal(abi.getAbiFromTarget('0.10.48'), '11')
  t.equal(abi.getAbiFromTarget('0.10.0'), '11')
  t.end()
})

test('getAbiFromTarget calculates correct Electron ABI', function (t) {
  t.throws(function () { abi.getAbiFromTarget(undefined, 'electron') })
  t.throws(function () { abi.getAbiFromTarget('7.2.0', 'electron') })
  t.equal(abi.getAbiFromTarget('1.4.0', 'electron'), '50')
  t.equal(abi.getAbiFromTarget('1.3.0', 'electron'), '49')
  t.equal(abi.getAbiFromTarget('1.2.0', 'electron'), '48')
  t.equal(abi.getAbiFromTarget('1.1.0', 'electron'), '48')
  t.equal(abi.getAbiFromTarget('1.0.0', 'electron'), '47')
  t.equal(abi.getAbiFromTarget('0.37.0', 'electron'), '47')
  t.equal(abi.getAbiFromTarget('0.36.0', 'electron'), '47')
  t.equal(abi.getAbiFromTarget('0.35.0', 'electron'), '46')
  t.equal(abi.getAbiFromTarget('0.34.0', 'electron'), '46')
  t.equal(abi.getAbiFromTarget('0.33.0', 'electron'), '46')
  t.equal(abi.getAbiFromTarget('0.32.0', 'electron'), '45')
  t.equal(abi.getAbiFromTarget('0.31.0', 'electron'), '45')
  t.equal(abi.getAbiFromTarget('0.30.0', 'electron'), '44')
  t.end()
})
