require('./gypbuild-test')
require('./pack-test')
require('./rc-test')
require('./strip-test')
require('./upload-test')
require('./util-test')
require('./integration-gyp-test')
require('./integration-cmake-test')
