build: off
skip_tags: true
version: "{build}"

# Set up build environment
environment:
  # Test against these versions of Node.js
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "14"

# Build on both platforms
platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test
